// Real photos (Wikimedia Commons, freely licensed) bundled under www/img.
// The list of available images and their credits is generated by scripts/fetch_images.py.
import credits from './data/image-credits.json';
import { esc } from './util.js';

// Must match scripts/gen-image-manifest.mjs
export function imgKey(title) {
  let h = 2166136261;
  const s = 'en:' + title;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0).toString(36);
}

function expand(k, c) {
  return {
    src: `img/${k}.jpg`,
    thumb: `img/${k}_t.jpg`,
    title: c.t,
    artist: c.a,
    license: c.l,
    file: c.f,
    page: `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(c.f)}`,
    w: c.w,
    h: c.h,
  };
}

/** { src, thumb, title, artist, license, file, page, w, h } or null */
export function image(title) {
  if (!title) return null;
  const k = imgKey(title);
  return credits[k] ? expand(k, credits[k]) : null;
}

export const imageCount = () => Object.keys(credits).length;
export const allCredits = () => Object.entries(credits).map(([k, c]) => expand(k, c));

export function creditText(img) {
  return `${img.artist || '作者不明'} / ${img.license}`;
}

/** Figure with photo + credit line. */
export function photoFigure(title, { cls = '', caption = '' } = {}) {
  const img = image(title);
  if (!img) return '';
  return `<figure class="photo ${cls}">
    <img src="${img.src}" alt="${esc(caption || title)}" loading="lazy" decoding="async" style="aspect-ratio:${img.w}/${img.h}">
    <figcaption>${caption ? `<span class="ph-cap">${esc(caption)}</span>` : ''}<span class="ph-credit">📷 ${esc(creditText(img))}・Wikimedia Commons</span></figcaption>
  </figure>`;
}
